server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql:///test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: service_user
  protocol:
    port: -1
  registry:
    address: zookeeper://192.168.245.199:2181
  consumer:
    check: false
    timeout: 10000
    retries: 3